#!/usr/bin/env bash
#ensure ip is in the path
PATH=$PATH:/sbin:/usr/sbin
IP=$(ip route get 8.8.8.8 | awk 'NR==1 {print $NF}')
echo "Using IP Address $IP"

export NO_BEACON_PLZ=1 #hack for now
export ZYRE_BIND="tcp://${IP}:13000"

./gateway keygen || true
echo '##################################################'
cat client.key
echo '##################################################'
echo "Starting in 5 seconds..."
sleep 5
./gateway $(hostname -f)
